### ISSUE TITLE
Repackage browser_action to page_action instead.

### ISSUE THREAD

**Issue by AkshatM** [kfishkin/butler#2]
Currently, this extension is packaged as a browser action, so that the icon and tooltip appears on _every_ page, regardless of whether or not it is a Quora page. It may not load the content script on a non-Quora , but it does mean I can send the redecorate command to it from even this GitHub page. 

This doesn't seem to make much sense given this is explicitly for Quora, so I would suggest repackaging this as a page action instead. A discussion of the differences are [here](http://ux.stackexchange.com/questions/33987/browser-extensions-page-action-or-browser-action).

The changes are simple: we will just need to replace `browser_action` in the manifest with `page_action` instead. The explanation is [here](https://developer.chrome.com/extensions/pageAction)

**Comment by kfishkin** [comment]
Sounds good to me! Try making the changes and see if they work.

**Comment by AkshatM** [comment]
So I'm running into issues. Simply changing the `browser_action` to `page_action` causes the Butler icon to no longer appear on Quora sites. Not quite sure why this is happening - I'm looking into the issue right now.

**Comment by AkshatM** [comment]
Page actions are hidden by default, apparently. They require use of the PageAction API. Using _that_ doesn't seem to work, but there is apparently another API called the Declarative Content API. Trying to use that ...

**Comment by AkshatM** [comment]
Turns out the regular Chrome.pageAction API works and all that was needed was to declare an explicit `background` page in the manifest to gain access to the API. See [this guide](https://blog.hartleybrody.com/chrome-extension/). I think we may want to consider restructuring `background.js` into a true background page, rather than as a content script.
