### ISSUE TITLE
Move comment decorator to background page

### ISSUE THREAD

**Issue by AkshatM** [kfishkin/butler#5]
Currently, we have exactly one popup that lets us specify a comment. Is this the right way to go, though? What if we want to expand the Quora butler's capabilities in the future? The popup's space is fairly small.

I think a better way to handle the butler is to move interface options to a special background page. Clicking the Butler icon in the URL tab can redirect to it, and users can set all options in there. 

What do you think?

**Comment by kfishkin** [comment]
i think we can cross that bridge when we come to it - since for now, we only have the 1 input field, i would hate to make users click to a special background page just to set that one thing.
